name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - ref

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0"

      - name: Build
        run: cd src/ && dotnet build

      - name: Test
        run: cd test/ && dotnet test --no-build --verbosity normal
